var words = [
"% % [pa1] /percent (Tw)/",
"21三體綜合症 21三体综合症 [er4 shi2 yi1 san1 ti3 zong1 he2 zheng4] /trisomy/Down's syndrome/",
"3C 3C [san1 C] /abbr. for computers, communications, and consumer electronics/China Compulsory Certificate (CCC)/",
"AA制 AA制 [A A zhi4] /to split the bill/to go Dutch/",
"AB制 AB制 [A B zhi4] /to split the bill (where the male counterpart foots the larger portion of the sum)/(theater) a system where two actors take turns in acting the main role, with one actor replacing the other if either is unavailable/",
"A咖 A咖 [A ka1] /class \"A\"/top grade/",
"A片 A片 [A pian4] /adult movie/pornography/",
"B型超聲 B型超声 [B xing2 chao1 sheng1] /type-B ultrasound/",
"B超 B超 [B chao1] /type-B ultrasound/abbr. for B型超聲|B型超声[B xing2 chao1 sheng1]/",
"C盤 C盘 [C pan2] /C drive or default startup drive (computing)/",
"DNA鑒定 DNA鉴定 [D N A jian4 ding4] /DNA test/DNA testing/",
"E仔 E仔 [E zai3] /MDMA (C11H15NO2)/",
"G弦褲 G弦裤 [G xian2 ku4] /G-string/",
"G點 G点 [G dian3] /Gräfenberg Spot/G-Spot/",
"K仔 K仔 [K zai3] /ketamine (slang)/",
"K他命 K他命 [k ta1 ming4] /ketamine (C13H16ClNO) (slang)/",
"K房 K房 [K fang2] /(slang) KTV/KTV room/",
"K書 K书 [K shu1] /to cram (Taiwan, from Taiwanese khè su 齧書, lit. to gnaw a book)/to study/see also 啃書|啃书[ken3 shu1]/",
"K歌 K歌 [K ge1] /karaoke (slang)/",
"K粉 K粉 [K fen3] /ketamine (slang)/",
"M巾 M巾 [M jin1] /(coll.) menstrual pad/",
"N檔 N档 [N dang4] /neutral (gear)/",
"OK繃 OK绷 [O K beng1] /band-aid (Tw)/",
"OK鏡 OK镜 [O K Jing4] /OK Lens, orthokeratology contact lens that helps reshape the cornea in order to eliminate nearsightedness or myopia/",
"O型腿 O型腿 [O xing2 tui3] /bow legs/bow-leggedness/",
"P圖 P图 [P tu2] /(Internet slang) to photoshop a picture/photoshopped picture/",
"P檔 P档 [P dang4] /park (gear)/program mode (on a digital camera)/",
"P民 P民 [P min2] /(slang) shitizen/commoner/hoi polloi/",
"Q Q [Q] /cute (loanword)/(of food) having a pleasant chewiness (like mochi, tapioca pearls, taro balls etc - foods with a springy or gel-like mouthfeel)/",
"T字帳 T字帐 [T zi4 zhang4] /T-account (accounting)/",
"T字褲 T字裤 [T zi4 ku4] /thong (underwear)/",
"T恤 T恤 [T xu4] /T-shirt/",
"T裇 T裇 [T xu1] /T-shirt/",
"USB手指 USB手指 [U S B shou3 zhi3] /USB flash drive/see also 閃存盤|闪存盘[shan3 cun2 pan2]/",
"USB記憶棒 USB记忆棒 [U S B ji4 yi4 bang4] /USB flash drive/see also 閃存盤|闪存盘[shan3 cun2 pan2]/",
"U凸內褲 U凸内裤 [U tu1 nei4 ku4] /contour pouch brief (men's underwear)/",
"U型枕 U型枕 [U xing2 zhen3] /travel pillow/",
"U形轉彎 U形转弯 [U xing2 zhuan3 wan1] /U-turn/",
"U盤 U盘 [U pan2] /USB flash drive/see also 閃存盤|闪存盘[shan3 cun2 pan2]/",
"V溝 V沟 [V gou1] /low neckline that reveals the cleavage/décolleté/gully/",
"X光 X光 [X guang1] /X-ray/",
"○ ○ [ling2] /character used in Taiwan as a substitute for a real name (like \"X\" in English)/variant of 〇[ling2]/",
"〇 〇 [ling2] /zero/",
"〡 〡 [yi1] /numeral 1 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/",
"〢 〢 [er4] /numeral 2 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/",
"〣 〣 [san1] /numeral 3 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/",
"〤 〤 [si4] /numeral 4 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/",
"〥 〥 [wu3] /numeral 5 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/",
"〦 〦 [liu4] /numeral 6 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/",
"〧 〧 [qi1] /numeral 7 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/",
"〨 〨 [ba1] /numeral 8 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/",
"〩 〩 [jiu3] /numeral 9 in Suzhou numeral system 蘇州碼子|苏州码子[Su1 zhou1 ma3 zi5]/",
"㐄 㐄 [kua4] /component in Chinese characters, mirror image of 夂[zhi3]/",
"㐅 㐅 [wu3] /archaic variant of 五[wu3]/",
"㐆 㐆 [yin3] /component in Chinese character 殷[yin1]/",
"㐌 㐌 [ta1] /variant of 它[ta1]/",
"㐖 㐖 [Ye4] /see 㐖毒[Ye4 du2]/",
"㐖毒 㐖毒 [Ye4 du2] /India (archaic)/",
"㐜 㐜 [chou2] /variant of 仇[chou2]/",
"㐡 㐡 [nuo4] /archaic variant of 懦[nuo4]/",
"㐤 㐤 [qiu2] /archaic variant of 求[qiu2]/",
"㐫 㐫 [xiong1] /old variant of 凶[xiong1]/",
"㐰 㐰 [xin4] /old variant of 信[xin4]/",
"㐺 㐺 [zhong4] /old variant of 眾|众[zhong4]/",
"㑳 㑇 [zhou4] /(old) beautiful/clever/",
"㑺 俊 [jun4] /old variant of 俊[jun4]/",
"㒳 㒳 [liang3] /old variant of 兩|两[liang3]/",
"㒸 㒸 [sui4] /archaic variant of 遂[sui4]/",
"㒺 罔 [wang3] /old variant of 罔[wang3]/",
"㓂 寇 [kou4] /old variant of 寇[kou4]/",
"㔾 㔾 [jie2] /\"seal\" radical in Chinese characters (Kangxi radical 26)/",
"㕁 却 [que4] /old variant of 卻|却[que4]/",
"㕑 厨 [chu2] /old variant of 廚|厨[chu2]/",
"㕥 㕥 [shen1] /old variant of 呻[shen1]/",
"㕥 以 [yi3] /old variant of 以[yi3]/",
"㕻 㕻 [pou3] /variant of 咅[pou3]/also pr. [tou4]/",
"㗂 㗂 [sheng3] /variant of 省[sheng3]/tight-lipped/to examine/to watch/to scour (esp. Cantonese)/",
"㗎 㗎 [jia4] /sentence-final particle, contraction of \"嘅呀\" (Cantonese)/see also 嘅[kai4]/",
"㘭 坳 [ao4] /variant of 坳[ao4]/",
"㚻 㚻 [ji1] /see 㚻姦|㚻奸[ji1 jian1]/",
"㚻姦 㚻奸 [ji1 jian1] /variant of 雞姦|鸡奸[ji1 jian1]/",
"㛂 㛂 [nuo3] /graceful/frail and petite/",
"㝄 㝄 [chun2] /old variant of 純|纯[chun2]/",
"㝇 㝇 [chun2] /old variant of 鶉|鹑[chun2]/",
"㝛 宿 [su4] /old variant of 宿[su4]/",
"㝠 冥 [ming2] /old variant of 冥[ming2]/",
"㝡 最 [zui4] /variant of 最[zui4]/",
"㝵 㝵 [ai4] /variant of 礙|碍[ai4]/",
"㝵 㝵 [de2] /to obtain/old variant of 得[de2]/",
"㞎 㞎 [ba3] /(baby talk) poop/see 㞎㞎[ba3 ba5]/",
"㞎㞎 㞎㞎 [ba3 ba5] /(baby talk) poop/",
"㞗 㞗 [qiu2] /(dialect) penis/dick/",
"㞙 㞙 [niao4] /old variant of 尿[niao4]/",
"㞞 㞞 [song2] /(coll.) semen/weak and incompetent/",
"㟁 岸 [an4] /variant of 岸[an4]/",
"㠀 岛 [dao3] /variant of 島|岛[dao3]/",
"㠯 以 [yi3] /old variant of 以[yi3]/",
"㠶 帆 [fan1] /variant of 帆[fan1]/",
"㡌 帽 [mao4] /old variant of 帽[mao4]/",
"㢘 廉 [lian2] /old variant of 廉[lian2]/",
"㢠 迥 [jiong3] /variant of 迥[jiong3]/",
"㢲 㢲 [xun4] /variant of 巽[xun4]/",
"㢴 㢴 [xi1] /old variant of 西[xi1]/",
"㤅 㤅 [ai4] /archaic variant of 愛|爱[ai4]/",
"㤙 恩 [en1] /variant of 恩[en1]/",
"㥁 㥁 [de2] /variant of 德[de2]/",
"㥏 㥏 [tian3] /ashamed/",
"㥦 惬 [qie4] /variant of 愜|惬[qie4]/",
"㥯 㥯 [yin3] /cautious/",
"㦂 㦂 [chang2] /old variant of 常[chang2]/",
"㧯 㧯 [lao3] /round-bottomed wicker basket/(dialect) to lift/to carry on one's shoulder/",
"㧱 拿 [na2] /old variant of 拿[na2]/",
"㨗 捷 [jie2] /variant of 捷[jie2]/quick/nimble/",
"㨪 晃 [huang3] /variant of 晃[huang3]/",
"㨿 据 [ju4] /variant of 據|据[ju4]/",
];
